version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: table
    versions:
    - 6.0.8
    - 6.0.9
    - 6.1.0
    - 6.3.0
    - 6.3.2
    - 6.3.4
    - 6.5.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: ioredis
    versions:
    - 4.22.0
    - 4.23.0
    - 4.24.2
    - 4.24.3
    - 4.24.4
    - 4.24.5
    - 4.24.6
    - 4.25.0
    - 4.26.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: nats
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: ora
    versions:
    - 5.3.0
