name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      nats:
        # Docker Hub image
        image: nats
        # Set health checks to wait until redis has started
        ports:
          - 4222:4222
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x, 17.x, 18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install lerna
      run: npm install lerna -g
    - name: Install
      run: npm install
    - name: Lerna bootstrap
      run: npx lerna bootstrap --force-local --hoist --ci -- --production=false
    - name: Run tests
      run: npm run test
